### ISSUE TITLE
String `expandedAbbr.detail` is not translatable

### ISSUE THREAD

**Issue by jens1o** [microsoft/vscode-emmet-helper#1]
See line: https://github.com/ramya-rao-a/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L47

This is impossible to translate.

**Comment by rzhao271** [comment]
For (own) reference the line is at https://github.com/microsoft/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L155 now.

**Comment by rzhao271** [comment]
Closing, fixed in [v2.0.9](https://www.npmjs.com/package/vscode-emmet-helper/v/2.0.9).

**Comment by rzhao271** [comment]
Verifier: code review
https://github.com/microsoft/vscode-emmet-helper/commit/7b44b9a33f473b168369e4cb8b731108baba36a1
