### ISSUE TITLE
Use the latest version of the Emmet module

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-emmet-helper#28]
The master branch at the moment is using version 0.5.10 of expand-abbreviation module with latest version of abbreviation and snippets module. See https://github.com/ramya-rao-a/expand-abbreviation/tree/0.5.10

We should move on to use the latest version of the expand-abbreviation module.

**Comment by ramya-rao-a** [comment]
From Sergey about version 0.6:

> Hey Ramya, 

just wanted to let you know that I’m going publish some breaking changes in @emmetio/expand-abbreviation module in v0.6

These changes are second argument with options. Moving towards web-based UI for Emmet customization, I’ve refactored and unified options layout for both markup & stylesheet abbreviations.
Also, I’ve created a config specs for customization. This config for storing global preferences and redefine them on syntax and/or project basis: https://github.com/emmetio/config

You can translate VSCode prefs to a config format and then use provided config resolver or simply pass manually resolved config to abbreviation expander with the following format: https://github.com/emmetio/config/blob/master/index.js#L39

**Comment by rzhao271** [comment]
Done. For verification, see `package.json` in https://github.com/microsoft/vscode-emmet-helper/commit/129f7ec691b963b7b437b42c8e3731cfd6af0402

There may still be bugs to resolve upstream such as https://github.com/emmetio/emmet/pull/638 but we are at least now using the latest Emmet dependency (at this time v2.3.0).

**Comment by rzhao271** [comment]
Reopening since it's still not the actual upstream repo yet.

**Comment by rzhao271** [comment]
Fixed by 209ed1ee3b90109ab8199e0308a2dd9a3481cd80
Verify by code review.
