### ISSUE TITLE
Remove limit on expansions

### ISSUE THREAD

**Issue by jsilvermist** [microsoft/vscode-emmet-helper#29]
I am unable to use VSCode for Emmet expansions since I need larger expansions which are able to be done in SublimeText. For example, `tag#id$$$*400>some-thing{PLACEHOLDER_1}+some-thing-else{PLACEHOLDER_2}`.

This is extremely useful for when parsing large datasets using a regex and inputting data in auto-numbered columns for XML data tables.

It would be nice to not have to keep SublimeText installed for this one small use case.

**Comment by wjcchls** [comment]
I know it's old threat but maybe someone will find it useful.
 
You can change Emmet creating multiple tags limit in file:
Microsoft VS Code\resources\app\extensions\emmet\node_modules\vscode-emmet-helper\out\emmetHelper.js
EDIT:
now it's: Microsoft VS Code\resources\app\extensions\emmet\node_modules\vscode-emmet-helper\lib\cjs\emmetHelper.js

    const multipleMatch = abbreviation.match(/\*(\d+)$/);
    if (multipleMatch) {
        return parseInt(multipleMatch[1], 10) <= 100;
    }

>         return parseInt(multipleMatch[1], 10) <= 100;   
- change 100 to number that you need, but be careful cause depending on your pc it can hang vscode if you put too much

**Comment by jsilvermist** [comment]
Hmm useful, but unless you can fix it in a way which persists across updates like the config file it's not really a proper fix.

**Comment by wjcchls** [comment]
True, but that's the job for Microsoft, not random user like me ^^

**Comment by rzhao271** [comment]
Closing this issue: this package is now using a `maxRepeat` of 1000.

The `maxRepeat` field is here:
https://github.com/emmetio/emmet/blob/master/packages/abbreviation/src/types.ts

And we're now calling it here:
https://github.com/microsoft/vscode-emmet-helper/blob/master/src/emmetHelper.ts#L681

**Comment by rzhao271** [comment]
Verification steps:
- Expand the abbreviation `ul>li*10000`
- Verify that 1002 lines are produced (2 for the `ul` 1000 for the `li`)
