### ISSUE TITLE
Bug: Parentheses inside text node are considered invalid hence expansion doesn't work

### ISSUE THREAD

**Issue by devanshj** [microsoft/vscode-emmet-helper#31]
`div{ foo (bar) baz }` should expand to `<div>foo (bar) baz</div>`. But currently this does not work because it's considered an invalid expression due to the following code

https://github.com/microsoft/vscode-emmet-helper/blob/05f86590aa88b88c8e4878c57b7f33b8b3256ed9/src/emmetHelper.ts#L492-L496

Restricting `(`  and `)` to be only next to `>`, `+`, `*` or  `^` misses the case where `(` or`)` are inside `{` and `}` that is in a text node.

Actual behavior:
![](http://g.recordit.co/WzP6OO0AnN.gif)

Expected behavior (as seen on [emmet's docs](https://docs.emmet.io/)):
![](http://g.recordit.co/v1wrir5LtP.gif)

I'll be sending a PR soon!

**Comment by roblourens** [comment]
verified ✔️
