### ISSUE TITLE
XSL self-closing tags not expanding properly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-emmet-helper#37]
As an example, for XSL files, `cp` should expand to `<xsl:copy select="|" />`, but right now it expands to `<xsl:copy select="|">|</xsl:copy>`.
This issue occurs for two reasons:
- In the snippets within `expand-full.js`, we have the mapping `"cp": "xsl:copy[select]"`, without the `/` at the end. Therefore, the expander interprets the tag as one with content in between.
- Even if `/` is added to the end, the XSL content is interpreted as HTML and expands to `<xsl:copy select="|">`, which is not a valid self-closing tag within XSL.

**Comment by rzhao271** [comment]
Note to self: this issue should be fixed after migrating to the latest Emmet

**Comment by rebornix** [comment]
It seems that in latest Insiders it still expands to `<xsl:copy select=""></xsl:copy>`

**Comment by rzhao271** [comment]
True. I'll currently leave that part as a wontfix, but I'll keep the issue open now that I realized:

- For `cp/`, Emmet doesn't automatically suggest `<xsl:copy select="" />` 🩸 
- When one expands `cp/` via the 'Expand Abbreviation' command it becomes `<xsl:copy select=""/>` with no space before the `/`, though this could just be preferences more than anything.

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/120203
