### ISSUE TITLE
SCSS emmet is more aggressive than previous versions

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/vscode-emmet-helper#42]
From: https://github.com/vuejs/vetur/issues/2522

In v2.0.9, the `doComplete` return `null` when I input `marginright`.
In v2.1.2, the `doComplete` return `marginright: |` completion when I input `marginright`.

Is it a correct result?

**Comment by rzhao271** [comment]
That doesn't look right to me.
I'm currently upgrading this package to use emmetio/emmet v2.3.0 instead of v2.1.6 and then I'll check to see what's happening

Will mark this issue as a bug for now.

**Comment by rzhao271** [comment]
Should be fixed in v2.2.1.
