### ISSUE TITLE
Extend the support for commonly used tags in emmet suggestions

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode-emmet-helper#5]
Commonly used tags were whitelisted, so that not every word triggers emmet suggestions which can be noise.

Emmet itself doesn't manage a white list and so we need to do so.

Current support: `['div', 'span', 'p', 'b', 'i', 'body', 'html', 'ul', 'ol', 'li', 'head', 'script', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'section']`

Should include:

- header
- footer

**Comment by ramya-rao-a** [comment]
From @guyvanbael in https://github.com/Microsoft/vscode/issues/32302#issue-249582065

- nav
- aside

**Comment by ramya-rao-a** [comment]
From  @opencreative  in https://github.com/Microsoft/vscode/issues/32317#issue-249613134

- table
- blockquote
- pre
- sup
- sub
- title
- plaintext
- noscript
- legend
- u
- code
- comment
- caption
- colgroup
- button
- big
- applet
- address
- strong
- small

**Comment by jens1o** [comment]
May I do that, please?

**Comment by ramya-rao-a** [comment]
Sure @jens1o

**Comment by ramya-rao-a** [comment]
Sorry @jens1o, I wanted to publish the update to emmet helper module for testing all the new changes needed for the Monday's build, so I went ahead and added the above to the commonly used tags.

https://github.com/Microsoft/vscode-emmet-helper/commit/7034f3cdd1e5066e46426e42163704c390ba7f5b

**Comment by jens1o** [comment]
Okay, when there's something new in queue, I'll file a pr. :)

I hate timezones in Open-Source Development...

**Comment by ramya-rao-a** [comment]
:) Another thing I can do is if there is anything emmet related that I need help on where you could send a PR, I can mention you in that issue and you can pick it up ?

**Comment by jens1o** [comment]
Yeah, that sounds cool!

**Comment by user3323** [comment]
@ramya-rao-a, I wonder, since ver. 1.15.0 - what is the path of the basic snippets file of Emmet, on Windows 7 ?

**Comment by ramya-rao-a** [comment]
@user3323 Which file are you referring to?

**Comment by user3323** [comment]
@ramya-rao-a, file called **snippets.json**, or I don't know how it's called now.

https://github.com/emmetio/emmet/blob/master/lib/snippets.json - with all these abbrs and snippets

**Comment by ramya-rao-a** [comment]
You can find the default snippets for new emmet here: https://github.com/emmetio/snippets

**Comment by ramya-rao-a** [comment]
And to customize them read: https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets

**Comment by user3323** [comment]
@ramya-rao-a, thanks for your response!

> You can find the default snippets for new emmet here: https://github.com/emmetio/snippets

I can see that there are files **html.json** and **css.json** do have all the basic snippets.
But I cannot find **html.json**, **css.json** or **snippets.json** in installed folder (_C:\Program Files\VS Code_) or in the user settings folder (_C:\Users\User\AppData\Roaming\Code_)

Well, actually, I can find html.json and css.json files in user settings folder (_C:\Users\User\AppData\Roaming\Code_), but they are - core's custom snippets files. Not Emmet.
And one snippets.json file in folder (_C:\Program Files\VS Code\resources\app\extensions\emmet\node_modules\vscode-emmet-helper\testData_), but the only thing it has is:
```
{
    "css": {
        "snippets": {
			"ch": "color:hsl(${1:0}, ${2:100}%, ${3:50}%);"
         }
    },
     "variables": {
		"lang": "fr"
    },
    "html": {
        "snippets": {
            "hey": "ul>li*2>span.hello"
        }
    }
}
```

I wonder where do these two files locate (or their snippets):
1) https://github.com/emmetio/snippets/blob/master/html.json
2) https://github.com/emmetio/snippets/blob/master/css.json

**Comment by ramya-rao-a** [comment]
@user3323 Can you share as to why you need the locations of these files?

**Comment by user3323** [comment]
@ramya-rao-a, to edit some of them. Some of them - to delete. It's not critical.

**Comment by ramya-rao-a** [comment]
The https://github.com/emmetio/snippets/ module gets bundled up with a bunch of other emmet modules into a single file which you can find at `C:\Program Files\VS Code\resources\app\extensions\emmet\node_modules\vscode-emmet-helper\out\expand\expand-full.js`

Also you can add your own custom snippets which will override the default ones

See https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets
