### ISSUE TITLE
css emmet with `!important`

### ISSUE THREAD

**Issue by yoyo930021** [microsoft/vscode-emmet-helper#58]
![](https://user-images.githubusercontent.com/22335334/109587494-1ed0f200-7b42-11eb-9483-c4a90fa159df.gif)

I don't know is it a bug?

Ref: https://github.com/vuejs/vetur/issues/2742

**Comment by rzhao271** [comment]
There's two bugs here:
1. `!` should have suggested `!important` instead of `!` and `!!!`. Emmet thinks the syntax is HTML within the `style` block for some reason.
2. `!im` should resolve to `!important` rather than `im !important`.

**Comment by rzhao271** [comment]
For point 1, see https://github.com/microsoft/vscode/issues/119736
For point 2, see https://github.com/emmetio/emmet/issues/650

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/120245
