### ISSUE TITLE
Problem with expanding long expressions

### ISSUE THREAD

**Issue by jdavid1385** [microsoft/vscode-emmet-helper#6]
I am having problems with expanding the expression below:

    `md-content[layout="column"].md-padding>md-subheader.md-no-sticky>div[layout=row layout-align=left]>md-button.md-raised.md-primary[ng-click="$ctrl.add()"]`

expanding only processes the chunk:

`div[layout=row layout-align=left]>md-button.md-raised.md-primary[ng-click="$ctrl.add()"]`

**Comment by ramya-rao-a** [comment]
@jdavid1385 This has been fixed upstream via https://github.com/emmetio/extract-abbreviation/issues/2

You will be able to see the fix in VS Code Insiders on Monday or you can wait for the VS Code 1.20 release
