### ISSUE TITLE
Emmet abbreviations still show up in suggestions despite disabling Emmet suggestions in user settings

### ISSUE THREAD

**Issue by EricTran5791** [microsoft/vscode-emmet-helper#7]
Replication steps:
1. Set the user setting `emmet.showExpandedAbbreviation` to `never`.
2. Install the VSCode extension Vetur: https://github.com/vuejs/vetur
3. Open a `.vue` file, in the CSS section type in `flex-direction: col`.
4. Notice that Emmet abbreviations still show up in the suggestions list.

![image](https://user-images.githubusercontent.com/6274717/31853584-e14a0d7e-b658-11e7-8c0b-f711f2573015.png)

Hopefully this makes sense. I'm referencing this issue: https://github.com/vuejs/vetur/issues/412

Thanks!

**Comment by ramya-rao-a** [comment]
The emmet settings need to be passed to the emmet helper by vetur which is not happening at the moment. @octref can fix this in vetur
