### ISSUE TITLE
esm output missing since version 2.8.5

### ISSUE THREAD

**Issue by dummdidumm** [microsoft/vscode-emmet-helper#79]
The package.json declares `"module": "./lib/esm/emmetHelper.js",` but the `esm` folder is missing from the package since version 2.8.5

Either remove the module field if this is deliberate or adjust the build pipeline so that the esm version is built and published.

**Comment by kermanx** [comment]
Sorry for this ping. This critical bug has been existing for more than one year, and is breaking downstream builds.

**Comment by aeschli** [comment]
Verified on https://www.npmjs.com/package/@vscode/emmet-helper?activeTab=code
